/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import Dao.DaoPost;
import Dao.DaoArea;
import Modelo.post;
import Dao.DaoEmployee;
import Modelo.area;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vista.Menu;


/**
 *
 * @author oscar
 */
public class infoVistaCargoCreate extends javax.swing.JFrame {
        
    DaoPost cargo=new DaoPost();
    private Menu menu;

    private infoVistaCargoCreate() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    
    public infoVistaCargoCreate(Menu menu) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);//esto hace que la ventana se situe en el centro de la pantalla
        txtId.setVisible(false);
        cargo.ListarCargo();
        this.menu = menu;
        DaoEmployee daoE=new DaoEmployee(); //listado de areas
        List<area> areas = daoE.obtenerAreas();
        for (area areaObj : areas) {
        String areaName =(areaObj.getName());//se almacena en una variable para evitar Dise�o
        cmbAreaCargo.addItem(areaName);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCargo = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        cmbStateCargo = new javax.swing.JComboBox<>();
        lblArea1 = new javax.swing.JLabel();
        btnCrearCargo = new javax.swing.JButton();
        lblCargoArea = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cmbAreaCargo = new javax.swing.JComboBox<>();

        lblCargo.setText("Cargo");

        cmbStateCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        lblArea1.setText("Estado");

        btnCrearCargo.setText("Crear");
        btnCrearCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCargoActionPerformed(evt);
            }
        });

        lblCargoArea.setText("Area");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStateCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnCrearCargo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCargoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAreaCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCargo)))
                    .addComponent(txtId))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoArea)
                    .addComponent(cmbAreaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStateCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea1)
                    .addComponent(btnCrearCargo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCargoActionPerformed
        DaoPost DCargo = new DaoPost();
        String inputcargo= txtCargo.getText();
        char stateCargo;
                if (cmbStateCargo.getSelectedItem()=="Activo"){
                        stateCargo='A';
                    }else {
                        stateCargo='I';
                    }
        
        String areaName = (String) cmbAreaCargo.getSelectedItem();
        DaoArea daoA=new DaoArea();
        int idArea = 0;
        try {
            idArea = daoA.retornaAreaId(areaName);
        } catch (SQLException ex) {
            Logger.getLogger(infoVistaCargoCreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            if (inputcargo != null && !inputcargo.trim().isEmpty()) { //primero se verifica que no este vacio el registro
                
                try {
                                boolean existe = DCargo.registroExiste(inputcargo);
                            if (existe) {
                                JOptionPane.showMessageDialog(null, "Ya existe un registro con nombre "+inputcargo);
                            } else {
                                DCargo.createCargo(inputcargo,idArea, stateCargo);
                                this.getMenu().ListarCargo();// Asumiendo que esto actualiza la lista de áreas
                                dispose();}
                            
                            } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null, "Error al verificar el registro: " + e.getMessage());
                                    e.printStackTrace(); // Para depuración
                            }
                
            }else {
            JOptionPane.showMessageDialog(null, "Registro vacío");
            }
    }//GEN-LAST:event_btnCrearCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoVistaCargoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoVistaCargoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoVistaCargoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoVistaCargoCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
new infoVistaCargoCreate().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCargo;
    private javax.swing.JComboBox<String> cmbAreaCargo;
    private javax.swing.JComboBox<String> cmbStateCargo;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargoArea;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
