/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import Modelo.area;
import Dao.DaoArea;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class infoVista extends javax.swing.JFrame {
        
    DaoArea area=new DaoArea();
    private Menu menu;

    private infoVista() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    
    public infoVista(Menu menu, String nro_registro) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);//esto hace que la ventana se situe en el centro de la pantalla
        area.Listar();
        this.setMenu(menu);
        txtId.setVisible(false);
        DaoArea dao=new DaoArea(); /*se importa la clase users*/
        area areaDatos=dao.consultar(nro_registro);
        txtId.setText(String.valueOf(areaDatos.getCode()));//se carga con el id pero no se ve
        txtarea.setText(String.valueOf(areaDatos.getName()));
        char state = areaDatos.getState();
        System.out.println("vista.infoVista.<init>()"+state);
        String stateString = String.valueOf(state);
        System.out.println("vista.infoVista.<init>()"+state);
        String stateName;
        if("A".equals(stateString)){
            stateName="Activo";
        }else {
            stateName="Inactivo";
        }
        cmbState.setSelectedItem(stateName);
    }

    infoVista(Menu menu) {
        initComponents();
        this.setLocationRelativeTo(null);//esto hace que la ventana se situe en el centro de la pantalla
        area.Listar();
        this.setMenu(menu);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtarea = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        cmbState = new javax.swing.JComboBox<>();
        lblArea1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnDeleteArea = new javax.swing.JButton();

        txtarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtareaKeyTyped(evt);
            }
        });

        lblArea.setText("Area");

        cmbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        lblArea1.setText("Estado");

        btnAceptar.setText("Actualizar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setText("jTextField1");
        txtId.setEnabled(false);

        btnDeleteArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/delete.png"))); // NOI18N
        btnDeleteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addComponent(txtarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteArea)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea1)
                    .addComponent(btnAceptar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DaoArea Darea = new DaoArea();
        String idtext=txtId.getText();
        int id =Integer.parseInt(idtext);
        String name= txtarea.getText();
        char state;
            if (name != null && !name.trim().isEmpty()) {
                boolean existe;
            try {
                existe = Darea.nombreExisteUpdate(name,id);
                if (existe) {
                            JOptionPane.showMessageDialog(null, "Ya existe un Area con nombre "+name);
                            } else {
                                    if (cmbState.getSelectedItem()=="Activo"){
                                            state='A';
                                        }else {
                                            state='I';
                                                }
                                                Darea.actualizar(id,name,state);
                                                this.getMenu().ListarArea();
                                                dispose();}
            } catch (SQLException ex) {
                Logger.getLogger(infoVista.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else {
                JOptionPane.showMessageDialog(null, "Registro Vacio" );
            }
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaKeyTyped
            char c = evt.getKeyChar();
            if (!Character.isLetter(c) && c != ' ') {
                evt.consume(); // Consume el evento si el carácter no es una letra ni un espacio
                }        // TODO add your handling code here:
    }//GEN-LAST:event_txtareaKeyTyped

    private void btnDeleteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAreaActionPerformed
                String idtext=txtId.getText();
                int id = Integer.parseInt(idtext);
                String name=txtarea.getText();
                DaoArea Darea = new DaoArea();
                int confirma=JOptionPane.showConfirmDialog(null, 
                "¿Está seguro de que desea eliminar este registro?", 
                "Confirmación de Eliminación", 
                JOptionPane.YES_NO_OPTION);
                System.out.println("esto salio " +confirma); //si es cero y no es uno
                if (confirma==0){
                    boolean vinculadoEmp;
                    try {
                        vinculadoEmp = Darea.registroVinculadoEmp(id);
                        if (vinculadoEmp){
                            JOptionPane.showMessageDialog(null, "Hay registros de empleados vinculados al Area "+name);
                        }else {
                            boolean vinculadoPost;
                             vinculadoPost = Darea.registroVinculadoPost(id);
                             if (vinculadoPost){
                            JOptionPane.showMessageDialog(null, "Hay registros de cargos vinculados al Area "+name);
                        }else {
                                Darea.DeleteArea(id);
                                this.getMenu().ListarArea();// Asumiendo que esto actualiza la lista de áreas
                                dispose();
                             }
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(infoVista.class.getName()).log(Level.SEVERE, null, ex);
                    }

            }else {
                System.out.println("no se confirmo");
            }
    }//GEN-LAST:event_btnDeleteAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnDeleteArea;
    private javax.swing.JComboBox<String> cmbState;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtarea;
    // End of variables declaration//GEN-END:variables
}
